class MACD:
    S = "MACD_SHORT"
    M = "MACD_MIDDLE"
    L = "MACD_LONG"

    S_S = "MACD_SHORT_SIGNAL"
    M_S = "MACD_MIDDLE_SIGNAL"
    L_S = "MACD_LONG_SIGNAL"

    S_O = "MACD_SHORT_OSCILLATOR"
    M_O = "MACD_MIDDLE_OSCILLATOR"
    L_O = "MACD_LONG_OSCILLATOR"

    S_GC = "MACD_SHORT_GOLDEN_CROSS"
    M_GC = "MACD_MIDDLE_GOLDEN_CROSS"
    L_GC = "MACD_LONG_GOLDEN_CROSS"

    S_DC = "MACD_SHORT_DEAD_CROSS"
    M_DC = "MACD_MIDDLE_DEAD_CROSS"
    L_DC = "MACD_LONG_DEAD_CROSS"
