services:
  upbit-green:
    container_name: upbit-green
    image: "autotrader"
    build: 
      context: . 
      dockerfile: Dockerfile 
    env_file:
      - .env 
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "8001:8000"
    expose:
      - "8001"
    command: ["python", "trade.py", "-c", "config.upbit.json", "-p", "8000"]
  
  bithumb-green:
    container_name: bithumb-green
    image: "autotrader"
    build: 
      context: . 
      dockerfile: Dockerfile 
    env_file:
      - .env 
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3001:3000"
    expose:
      - "3001"
    command: ["python", "trade.py", "-c", "config.bithumb.json", "-p", "3000"]

