services:
  bithumb-container:
    container_name: bithumb-blue
    env_file:
      - .env.bithumb
    environment:
      TZ: "Asia/Seoul"
    image: autotrading:v1
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - "3000:3000"
    expose:
      - "3000"
    build: .
    healthcheck:
      test: >
        bash -c ': > /dev/tcp/localhost/3000' || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
    volumes:
      - ./log:/app/log
  upbit-container:
    container_name: upbit-blue
    env_file:
      - .env.upbit
    environment:
      TZ: "Asia/Seoul"
    image: autotrading:v1
    command: [ "uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "8000:8000"
    expose:
      - "8000"
    build: .
    healthcheck:
      test: >
        bash -c ': > /dev/tcp/localhost/8000' || exit 1
      interval: 30s
      timeout: 10s
      retries: 2
    volumes:
      - ./log:/app/log

