

class MACD:
    UP = "MACD_UP"
    MID = "MACD_MID"
    LOW = "MACD_LOW"

    UP_SLOPE = "UP_SLOPE"
    MID_SLOPE = "MID_SLOPE"
    LOW_SLOPE = "LOW_SLOPE"

    SIGNAL = "SIGNAL"

    UP_HIST = "UP_HIST"
    MID_HIST = "MID_HIST"
    LOW_HIST = "LOW_HIST"